name: Unlock Terraform State

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: 'Lock ID'
        required: true
        default: 'your-lock-id'

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  UnlockTerraformState:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::701722125320:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Unlock Terraform State
        run: |
          echo "** Unlocking Terraform State **"
          terraform force-unlock ${{ github.event.inputs.lock_id }}